# 1.[GAUSS-51802] : Failed to obtain the environment variable "GPHOME", please import environment variable.
- 报错信息
```
(myenv) [root@master script]# ./gs_expansion -U omm -G dbgrp -X /opt/openGausssource/cluster_config.xml -h 192.168.131.21
[GAUSS-51802] : Failed to obtain the environment variable "GPHOME", please import environment variable.
```
- 报错原因    
  root用户下未设置环境变量
- 处理    
```
export GPHOME=/opt/openGausssource
export PGHOST=192.168.131.20
export GAUSSHOME=/opt/openGauss
```

# 2.Exception: cp file failed
- 报错信息
```
(myenv) [root@master script]# ./gs_expansion -U omm -G dbgrp -X /opt/openGausssource/cluster_config.xml -h 192.168.131.21
Traceback (most recent call last):
  File "/opt/openGausssource/script/gs_expansion", line 39, in <module>
    copy_lib()
  File "/opt/openGausssource/script/gspylib/common/copy_python_lib.py", line 14, in copy_lib
    raise Exception("cp file failed.\nError:%s\nThe cmd is: %s\n" %
Exception: cp file failed.
Error:cp: cannot stat ‘/opt/openGausssource/script/gspylib/common/../../../lib/bcrypt/lib3.12/_bcrypt.abi3.so’: No such file or directory
The cmd is: cp /opt/openGausssource/script/gspylib/common/../../../lib/bcrypt/lib3.12/_bcrypt.abi3.so /opt/openGausssource/script/gspylib/common/../../../lib/bcrypt/
```
- 报错原因   
  当配置多python版本时copy_python_lib.py中的sys.version_info[1]获取错误导致文件找不到
- 处理   
  使用正确的python版本
```
#禁止自动激活base（root/omm用户都处理）
conda config --set auto_activate_base false
#配置默认进入虚拟环境
vi ~/.bashrc
conda activate myenv
```

# 3.Permission denied: '/opt/openGausssource/script/gspylib/common/copy_python_lib.py'
- 报错信息   
```
/opt/openGausssource/script/gs_sshexkey:1354: SyntaxWarning: invalid escape sequence '\m'
  cmd += '\mv {} {} && '.format(' '.join(bin_files), clib)
Traceback (most recent call last):
  File "/opt/openGausssource/script/gs_sshexkey", line 53, in <module>
    from gspylib.common.copy_python_lib import copy_lib
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
PermissionError: [Errno 13] Permission denied: '/opt/openGausssource/script/gspylib/common/copy_python_lib.py'
Traceback (most recent call last):
  File "/opt/openGauss/install/om/script/gspylib/threads/SshTool.py", line 248, in createTrust
    raise Exception(ErrorCode.GAUSS_516["GAUSS_51632"] % "gs_sshexkey" +
Exception
```
- 报错原因   
  ssh 登录到slaver后omm用户无权限访问文件夹
- 处理      
  修改/opt/openGausssource目录权限为omm所属

# 4.192.168.131.128 in xml is not consistent with that in cluster.XML configure string item failed
- 报错信息
```
(myenv) [root@master script]# ./gs_expansion -U omm -G dbgrp -X /opt/openGausssource/cluster_config.xml -h 192.168.131.21
The cluster no need create ssh trust
Traceback (most recent call last):
  File "/opt/openGausssource/script/gs_expansion", line 735, in <module>
    expansion.getExpansionInfo()
  File "/opt/openGausssource/script/gs_expansion", line 428, in getExpansionInfo
    self._getClusterInfoDict()
  File "/opt/openGausssource/script/gs_expansion", line 240, in _getClusterInfoDict
    self.check_xml_config()
  File "/opt/openGausssource/script/gs_expansion", line 555, in check_xml_config
    expand_cluster_info.compare_cluster_info(static_cluster_info,
  File "/opt/openGausssource/script/gs_expansion", line 719, in compare_cluster_info
    self.compare_dict(static_cluster_info.__dict__, xml_cluster_info.__dict__)
  File "/opt/openGausssource/script/gs_expansion", line 700, in compare_dict
    self.compare_list(a_dict.get(a_key), b_dict.get(a_key))
  File "/opt/openGausssource/script/gs_expansion", line 635, in compare_list
    self.compare_dict(a_list[a_index].__dict__, b_list_node.__dict__)
  File "/opt/openGausssource/script/gs_expansion", line 700, in compare_dict
    self.compare_list(a_dict.get(a_key), b_dict.get(a_key))
  File "/opt/openGausssource/script/gs_expansion", line 652, in compare_list
    self.compare_string(a_list[a_index], b_list[a_index])
  File "/opt/openGausssource/script/gs_expansion", line 664, in compare_string
    raise Exception((ErrorCode.GAUSS_357["GAUSS_35711"] %
Exception: [GAUSS-35711] 192.168.131.128 in xml is not consistent with that in cluster.XML configure string item failed: ['name', 'appPath', 'logPath', 'dbNodes', 'node: master', 'name', 'backIps', '192.168.131.128'] . Static config 192.168.131.128. XML config 192.168.131.20

```
- 报错原因
  服务器ip修改变更后，静态配置文件未变更
- 处理
```
gs_om -t generateconf -X /opt/openGausssource/cluster_config.xml  --distribute
```
